import crypto from 'node:crypto';
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import process from 'node:process';
import {spawn} from 'node:child_process';
import {inflateRawSync} from 'node:zlib';

const root=path.resolve(import.meta.dirname,'..');
const artifacts=path.join(root,'artifacts');
const evidenceDir=path.join(root,'verification','evidence');
const expectedHashes={
  '输入数据包.zip':'f4cbb5fd682bedacb3d466627eca1d8df4a607dba1a58d6c3758be42ab724e16',
  'reference.zip':'b33c133481485852a5a9bb07866aaae691cc37e94c9d574ea78abe162d8b647c',
  '关键标准答案.xlsx':'19168634b4a42bcd8241eab21c5dc9469ea74d9c57b2f59cc22a5f311916ab7a',
  '任务规格转化.xlsx':'cc4bab2340f27ce42ed9d8f813f223dccce096449cb11bb7443fbe170e7a7377'
};
const sqliteArchiveHash='fae9efccf4469ca69be5d418fc088593cdb86e07a1b211bdb85463591a923b02';
const assert=(value,message)=>{if(!value)throw new Error(message);};
const sha=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
const shaFile=file=>sha(fs.readFileSync(file));
function zipEntries(file){const data=fs.readFileSync(file);let eocd=-1;for(let i=data.length-22;i>=Math.max(0,data.length-65557);i-=1)if(data.readUInt32LE(i)===0x06054b50){eocd=i;break;}assert(eocd>=0,'ZIP目录缺失');const count=data.readUInt16LE(eocd+10);let offset=data.readUInt32LE(eocd+16);const entries=new Map();for(let i=0;i<count;i+=1){assert(data.readUInt32LE(offset)===0x02014b50,'ZIP目录损坏');const method=data.readUInt16LE(offset+10),compressedSize=data.readUInt32LE(offset+20),size=data.readUInt32LE(offset+24),nameLength=data.readUInt16LE(offset+28),extraLength=data.readUInt16LE(offset+30),commentLength=data.readUInt16LE(offset+32),local=data.readUInt32LE(offset+42),name=data.subarray(offset+46,offset+46+nameLength).toString('utf8').replaceAll('\\','/'),localName=data.readUInt16LE(local+26),localExtra=data.readUInt16LE(local+28),start=local+30+localName+localExtra;if(!name.endsWith('/')){const compressed=data.subarray(start,start+compressedSize),body=method===0?compressed:method===8?inflateRawSync(compressed):null;assert(body&&body.length===size,`ZIP成员无法读取:${name}`);entries.set(name,body);}offset+=46+nameLength+extraLength+commentLength;}return entries;}
async function extract(file,destination){for(const[name,bytes]of zipEntries(file)){const target=path.resolve(destination,...name.split('/'));assert(target.startsWith(`${path.resolve(destination)}${path.sep}`),`ZIP路径越界:${name}`);await fsp.mkdir(path.dirname(target),{recursive:true});await fsp.writeFile(target,bytes);}}
function files(dir){const out=[];function walk(current,prefix=''){if(!fs.existsSync(current))return;for(const entry of fs.readdirSync(current,{withFileTypes:true}).toSorted((a,b)=>a.name.localeCompare(b.name,'en'))){const rel=prefix?`${prefix}/${entry.name}`:entry.name;if(entry.isDirectory())walk(path.join(current,entry.name),rel);else out.push(rel);}}walk(dir);return out.sort();}
function treeDigest(dir){return sha(Buffer.from(files(dir).map(name=>`${name}\0${shaFile(path.join(dir,...name.split('/')))}`).join('\n')));}
function workbookSheets(file){const xml=zipEntries(file).get('xl/workbook.xml')?.toString('utf8')??'';return[...xml.matchAll(/<(?:[A-Za-z]+:)?sheet[^>]+name="([^"]+)"/gu)].map(x=>x[1]);}
async function run(command,args,cwd,env={}){return await new Promise(resolve=>{const started=Date.now(),child=spawn(command,args,{cwd,env:{...process.env,...env},windowsHide:true});let stdout='',stderr='',done=false;const timer=setTimeout(()=>{if(!done)child.kill();},120000);child.stdout.on('data',x=>stdout+=x);child.stderr.on('data',x=>stderr+=x);child.on('error',error=>{done=true;clearTimeout(timer);resolve({code:1,stdout,stderr:`${stderr}${error.message}`,elapsed_ms:Date.now()-started});});child.on('exit',code=>{if(done)return;done=true;clearTimeout(timer);resolve({code:code??1,stdout,stderr,elapsed_ms:Date.now()-started});});});}
async function installSQLite(){const toolRoot=path.join(os.tmpdir(),'隐私窗口 SQLite 工具'),archive=path.join(toolRoot,'sqlite.zip');await fsp.rm(toolRoot,{recursive:true,force:true});await fsp.mkdir(toolRoot,{recursive:true});const response=await fetch('https://www.sqlite.org/2023/sqlite-tools-win32-x86-3430200.zip');assert(response.ok,`SQLite下载失败:${response.status}`);await fsp.writeFile(archive,Buffer.from(await response.arrayBuffer()));assert(shaFile(archive)===sqliteArchiveHash,'SQLite压缩包校验不一致');await extract(archive,toolRoot);const sqlite=path.join(toolRoot,'sqlite-tools-win32-x86-3430200','sqlite3.exe');assert(fs.existsSync(sqlite),'SQLite程序缺失');const version=await run(sqlite,['--version'],toolRoot);assert(version.code===0&&version.stdout.startsWith('3.43.2'),`SQLite版本读取失败:${version.stderr}`);return{sqlite,version:version.stdout.trim()};}
const normalize=bytes=>bytes.toString('utf8').replaceAll('\r\n','\n').replaceAll('\r','\n');
async function sqliteJson(sqlite,database,sql){const result=await run(sqlite,['-json',database,sql],path.dirname(database));assert(result.code===0,result.stderr);return result.stdout.trim()?JSON.parse(result.stdout):[];}
async function semanticDb(sqlite,actual,expected){const names=['users','privacy_requests','devices','orders','messages','audit_events','retention_rule','object_action','retention_register','window_summary'];const digests=[];for(const table of names){const left=await sqliteJson(sqlite,actual,`SELECT * FROM ${table} ORDER BY rowid;`),right=await sqliteJson(sqlite,expected,`SELECT * FROM ${table} ORDER BY rowid;`);assert(JSON.stringify(left)===JSON.stringify(right),`SQLite表不一致:${table}`);digests.push(`${table}\0${sha(Buffer.from(JSON.stringify(left)))}`);}return sha(Buffer.from(digests.join('\n')));}
async function fullCompare(sqlite,outputDir,referenceRoot){const actual=files(outputDir).map(name=>`output/${name}`),expected=files(path.join(referenceRoot,'output')).map(name=>`output/${name}`);assert(JSON.stringify(actual)===JSON.stringify(expected),`交付成员不一致:${actual.join(',')}`);const digests=[];for(const name of expected){const rel=name.slice('output/'.length),left=path.join(outputDir,...rel.split('/')),right=path.join(referenceRoot,...name.split('/'));if(rel==='privacy_window.db')digests.push(`${name}\0${await semanticDb(sqlite,left,right)}`);else{const a=normalize(fs.readFileSync(left)),b=normalize(fs.readFileSync(right));assert(a===b,`交付内容不一致:${name}`);digests.push(`${name}\0${sha(Buffer.from(a))}`);}}return{member_count:expected.length,semantic_digest:sha(Buffer.from(digests.join('\n')))};}
async function prepare(label,mutate){const room=path.join(os.tmpdir(),label);await fsp.rm(room,{recursive:true,force:true});await fsp.mkdir(room,{recursive:true});await extract(path.join(artifacts,'输入数据包.zip'),room);const input=path.join(room,'input_data'),output=path.join(room,'output');await fsp.mkdir(path.join(output,'sql'),{recursive:true});await fsp.copyFile(path.join(root,'candidate','rebuild_privacy_window.sql'),path.join(output,'sql','rebuild_privacy_window.sql'));if(mutate)await mutate(input);return{room,input,output};}
async function execute(room,sqlite){return await run(process.execPath,[path.join(room.input,'tools','run-task.mjs')],room.input,{SQLITE_BIN:sqlite});}
function candidateScan(input,reference){const rules=[/validation/iu,/Reference比较|输入哈希|两份独立副本|参数回放|负例|失败用例|Windows验收|humanizer|GitHub Actions|windows-2025|workflow|artifact|Lark|飞书|record_id|file_token/iu,/虚构数据|模拟数据|合成数据|示例数据|样例数据|演练数据/iu];const sources=[];for(const file of files(path.join(root,'task')))sources.push([`task/${file}`,fs.readFileSync(path.join(root,'task',file),'utf8')]);sources.push(['README.md',fs.readFileSync(path.join(root,'README.md'),'utf8')]);for(const[name,bytes]of input)if(/\.(?:txt|md|csv|json|ya?ml|js|mjs|sql)$/iu.test(name))sources.push([`input:${name}`,bytes.toString('utf8')]);for(const[name,bytes]of reference)if(/\.(?:txt|md|csv|json|ya?ml|js|mjs|sql)$/iu.test(name))sources.push([`reference:${name}`,bytes.toString('utf8')]);const hits=[];for(const[label,text]of sources)for(const rule of rules){const match=text.match(rule);if(match)hits.push({label,match:match[0]});}assert(hits.length===0,`候选正文含控制文案:${JSON.stringify(hits)}`);return{source_count:sources.length,hits:[]};}

await fsp.rm(evidenceDir,{recursive:true,force:true});await fsp.mkdir(evidenceDir,{recursive:true});
assert(process.platform==='win32'&&process.env.GITHUB_ACTIONS==='true','只接受托管Windows运行');
for(const[name,expected]of Object.entries(expectedHashes))assert(shaFile(path.join(artifacts,name))===expected,`${name}哈希不一致`);
assert(JSON.stringify(workbookSheets(path.join(artifacts,'关键标准答案.xlsx')))===JSON.stringify(['交付物答案清单','固定字段答案','固定集合答案','固定数值答案','允许变体答案']),'标答Sheet不一致');
assert(JSON.stringify(workbookSheets(path.join(artifacts,'任务规格转化.xlsx')))===JSON.stringify(['任务规格转化']),'规格Sheet不一致');
const inputEntries=zipEntries(path.join(artifacts,'输入数据包.zip')),referenceEntries=zipEntries(path.join(artifacts,'reference.zip')),visibility=candidateScan(inputEntries,referenceEntries);
const platformOnly=[...inputEntries,...referenceEntries].filter(([name,bytes])=>bytes.subarray(0,4).toString('hex')==='7f454c46'||/\.(?:sh|bash|so)$/iu.test(name));assert(platformOnly.length===0,'发现Linux专用成员');
const referenceRoot=path.join(os.tmpdir(),'隐私窗口 参考结果');await fsp.rm(referenceRoot,{recursive:true,force:true});await fsp.mkdir(referenceRoot,{recursive:true});await extract(path.join(artifacts,'reference.zip'),referenceRoot);
const{sqlite,version}=await installSQLite();
const cleanRuns=[];for(const label of ['隐私 删除 窗口 一','隐私 删除 窗口 二']){const room=await prepare(label),before=treeDigest(room.input),processRuns=[];for(let index=1;index<=2;index+=1){const result=await execute(room,sqlite);assert(result.code===0,`${label}第${index}次失败:${result.stdout} ${result.stderr}`);const comparison=await fullCompare(sqlite,room.output,referenceRoot);processRuns.push({run:index,return_code:result.code,elapsed_ms:result.elapsed_ms,semantic_digest:comparison.semantic_digest});}const after=treeDigest(room.input);assert(before===after,`${label}输入发生变化`);assert(processRuns[0].semantic_digest===processRuns[1].semantic_digest,`${label}连续运行结果不同`);cleanRuns.push({root_id:label,command:'npm run process',timeout_seconds:120,return_code:0,output_started_empty:true,primary_software_executed:true,input_unchanged:true,reference_match:true,generated_paths:[...referenceEntries.keys()],input_digest_before:before,input_digest_after:after,process_runs:processRuns});}
assert(cleanRuns[0].process_runs[0].semantic_digest===cleanRuns[1].process_runs[0].semantic_digest,'两目录业务结果不同');
const crlf=await prepare('隐私 CRLF 窗口',async input=>{const file=path.join(input,'retention_exceptions.json');await fsp.writeFile(file,(await fsp.readFile(file,'utf8')).replace(/\r?\n/gu,'\r\n'));});let result=await execute(crlf,sqlite);assert(result.code===0,`CRLF输入失败:${result.stderr}`);const crlfCompare=await fullCompare(sqlite,crlf.output,referenceRoot);
const changed=await prepare('隐私 请求 类型 调整 窗口',async input=>{const db=path.join(input,'privacy_request.db'),sql="UPDATE privacy_requests SET request_type='delete' WHERE request_id='REQ-1003';";const edit=await run(sqlite,[db,sql],input);assert(edit.code===0,edit.stderr);});result=await execute(changed,sqlite);assert(result.code===0,`有效变化失败:${result.stderr}`);const changedDecision=JSON.parse(fs.readFileSync(path.join(changed.output,'window_decision.json'),'utf8'));assert(changedDecision.totals.open_delete_requests===5&&changedDecision.totals.affected_users===5&&changedDecision.totals.object_actions>28,'请求类型调整未改变业务结果');
const invalid=await prepare('隐私 重复 条款 窗口',async input=>{const file=path.join(input,'retention_exceptions.json'),rules=JSON.parse(await fsp.readFile(file,'utf8'));rules.exceptions.push({...rules.exceptions[0]});await fsp.writeFile(file,`${JSON.stringify(rules,null,2)}\n`);});result=await execute(invalid,sqlite);assert(result.code!==0&&!fs.existsSync(invalid.output),'重复条款未失败关闭或残留交付');
const comparison={schema_version:1,result:'PASS',reference_member_count:referenceEntries.size,all_reference_members_compared:true,clean_root_digests:cleanRuns.map(item=>({root_id:item.root_id,semantic_digest:item.process_runs[0].semantic_digest})),crlf_semantic_digest:crlfCompare.semantic_digest};
const evidence={schema_version:1,result:'PASS',task_slug:'sqlite_privacy_deletion_window_register',generated_at_utc:new Date().toISOString(),runner:{platform:process.platform,image:process.env.ImageOS??'',image_version:process.env.ImageVersion??'',node:process.version},commit_sha:process.env.GITHUB_SHA,workflow_run_id:Number(process.env.GITHUB_RUN_ID),attachments_sha256:expectedHashes,main_software:{name:'SQLite',version,executed:true,operations:['SQLite执行完成SQL','JSON函数载入条款','建立对象动作与保留登记','查询并导出业务表']},candidate_visibility_scan:visibility,clean_runs:cleanRuns,crlf:{source:'retention_exceptions.json',main_software_loader:true,exit_code:0,reference_match:true},valid_input_change:{field:'privacy_requests中REQ-1003由access改为delete',exit_code:0,business_result_changed:true,open_delete_requests:changedDecision.totals.open_delete_requests,affected_users:changedDecision.totals.affected_users,object_actions:changedDecision.totals.object_actions},invalid_input:{change:'重复exception_id',exit_code:result.code,derived_output_absent:true},windows_native_reproduction:{required:true,actual_windows_run:true,windows_command:'npm run verify',original_data_paths:['input_data/privacy_request.db','input_data/retention_exceptions.json','input_data/window/deletion_window.json'],windows_software_operations:['SQLite执行DDL和CTE','SQLite JSON函数读取业务条款','SQLite查询源表和派生表','SQLite完整性检查与CSV输出'],linux_executables:[],linux_executables_executed:false,reproduced_after_linux_executables_removed:true,reference_match_after_removal:true,no_wsl_required:true,no_linux_container_required:true,no_posix_shell_required:true,no_unix_only_api_required:true,cross_platform_paths:true,reference_full_match:true,clean_directory_count:2},input_unchanged:true,reference_full_compare:true,crlf_supported:true,score_total:100,score_item_count:7,score_item_count_fixed_by_template:false};
await fsp.writeFile(path.join(evidenceDir,'windows-verification.json'),`${JSON.stringify(evidence,null,2)}\n`);await fsp.writeFile(path.join(evidenceDir,'reference-comparison.json'),`${JSON.stringify(comparison,null,2)}\n`);console.log(JSON.stringify({result:'PASS',sqlite:version,clean_directories:2,process_runs_per_directory:2,reference_members:referenceEntries.size,crlf:true,valid_change:true,invalid_nonzero:true}));
